services:
  atiende:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    networks:
      - prittor-proxy

networks:
  prittor-proxy:
    external: true
